// <auto-generated />
using System;
using DartScorerLight.Business.Repositories.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DartScorerLight.Business.Migrations
{
    [DbContext(typeof(DartScorerLightContext))]
    partial class DartScorerLightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("DartScorerLight.Business.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PlayerId");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DartScorerLight.Business.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ChangeDateUtc");

                    b.Property<DateTime>("CreateDateUtc");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nickname");

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DartScorerLight.Business.Models.Game", b =>
                {
                    b.HasOne("DartScorerLight.Business.Models.Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
